import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TECH-NEWS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Post News: <a href="./api/news">./api/news</a>
        </h1>
      </main>
    </div>
  );
}
